/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs.index'
import { Route as SetlistsIndexRouteImport } from './routes/setlists.index'
import { Route as SongsNewRouteImport } from './routes/songs.new'
import { Route as SongsIdRouteImport } from './routes/songs.$id'
import { Route as SetlistsIdRouteImport } from './routes/setlists.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIndexRoute = SetlistsIndexRouteImport.update({
  id: '/setlists/',
  path: '/setlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsNewRoute = SongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIdRoute = SongsIdRouteImport.update({
  id: '/songs/$id',
  path: '/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIdRoute = SetlistsIdRouteImport.update({
  id: '/setlists/$id',
  path: '/setlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setlists/$id': typeof SetlistsIdRoute
  '/songs/$id': typeof SongsIdRoute
  '/songs/new': typeof SongsNewRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setlists/$id': typeof SetlistsIdRoute
  '/songs/$id': typeof SongsIdRoute
  '/songs/new': typeof SongsNewRoute
  '/setlists': typeof SetlistsIndexRoute
  '/songs': typeof SongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setlists/$id': typeof SetlistsIdRoute
  '/songs/$id': typeof SongsIdRoute
  '/songs/new': typeof SongsNewRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setlists/$id'
    | '/songs/$id'
    | '/songs/new'
    | '/setlists/'
    | '/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setlists/$id'
    | '/songs/$id'
    | '/songs/new'
    | '/setlists'
    | '/songs'
  id:
    | '__root__'
    | '/'
    | '/setlists/$id'
    | '/songs/$id'
    | '/songs/new'
    | '/setlists/'
    | '/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetlistsIdRoute: typeof SetlistsIdRoute
  SongsIdRoute: typeof SongsIdRoute
  SongsNewRoute: typeof SongsNewRoute
  SetlistsIndexRoute: typeof SetlistsIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/': {
      id: '/setlists/'
      path: '/setlists'
      fullPath: '/setlists/'
      preLoaderRoute: typeof SetlistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/new': {
      id: '/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof SongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$id': {
      id: '/songs/$id'
      path: '/songs/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof SongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/$id': {
      id: '/setlists/$id'
      path: '/setlists/$id'
      fullPath: '/setlists/$id'
      preLoaderRoute: typeof SetlistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetlistsIdRoute: SetlistsIdRoute,
  SongsIdRoute: SongsIdRoute,
  SongsNewRoute: SongsNewRoute,
  SetlistsIndexRoute: SetlistsIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
